baseURL = 'https://pn11.github.io/blog/'
languageCode = 'ja-jp'
title = "pn11's blog"
theme = "beautifulhugo"

[markup.goldmark.renderer]
 unsafe = true

[Params]
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true

  [services]
    [services.disqus]
      shortname = 'pn11-blog'
