baseURL = 'https://pn11.github.io/blog/'
languageCode = 'ja-jp'
title = "pn11's blog"
theme = "beautifulhugo"

# v0.102.3 時点での書き方？
disqusShortname = "pn11-blog"

[markup.goldmark.renderer]
  unsafe = true

[Params]
  socialShare = true
  delayDisqus = false
  showRelatedPosts = true

#[services]
#  [services.disqus]
#    shortname = 'pn11-blog'
